# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_exam_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='name',
            new_name='choice_name',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='name',
            new_name='quiz_name',
        ),
    ]
